window.PersonaLibraryDataFragments = window.PersonaLibraryDataFragments || {};
window.PersonaLibraryDataFragments.skillLibrary = window.PersonaLibraryDataFragments.skillLibrary || {};
Object.assign(window.PersonaLibraryDataFragments.skillLibrary, {
  'ui-expert':[
    {name:'Interface hierarchy and visual communication',status:'Synthesized',definition:'Use composition, typography, spacing, color, and visual emphasis to make meaning and priority immediately legible.',triggers:'Dense or competing content · Important action is hard to find · Visual emphasis conflicts with task priority',workflows:'Translate intent into interface structure · Craft the core interaction and visual system',actions:'Establishes hierarchy, tests emphasis against real content, and removes decoration that competes with the task.',evidence:'Synthesized from interface-design tasks and visual usability heuristics · Validate with critique using realistic content'},
    {name:'Contextual visual judgment and composition',status:'Synthesized',definition:'Recognize and shape the relationships between hierarchy, proportion, rhythm, density, typography, color, spacing, contrast, grouping, and visual tone, then adapt them to the product context.',triggers:'Interface feels generic, noisy, flat, or tonally wrong · New visual language is needed · Pattern consistency conflicts with the task',workflows:'Translate intent into interface structure · Craft the core interaction and visual system · Extend and govern the design system · Resolve a pattern or constraint conflict',actions:'Studies relevant visual and interaction references, tests hierarchy and composition with realistic content, separates preference from rationale, and makes contextual tradeoffs explicit.',evidence:'Synthesized from visual-design principles, Material layout guidance, and design-system contribution practice · Validate with a comparative visual study, critique, and realistic prototype review'},
    {name:'Interaction states and behavior design',status:'Synthesized',definition:'Design the complete behavioral model of an interface, including defaults, loading, errors, empty states, transitions, and recovery.',triggers:'Happy path is clear but failure path is not · New async behavior · Users lose context after an action',workflows:'Craft the core interaction and visual system · Repair a broken or confusing interface',actions:'Maps states and transitions, defines feedback and exit paths, and checks that users can recover without guessing.',evidence:'Synthesized from O*NET testing responsibilities and usability heuristics · Validate through state walkthroughs and usability sessions'},
    {name:'Responsive and adaptive layout',status:'Synthesized',definition:'Translate an interface across screen sizes, input modes, content lengths, and environmental constraints without losing clarity or control.',triggers:'New breakpoint or device · Content is variable · Layout clips or becomes ambiguous on smaller screens',workflows:'Craft the core interaction and visual system · Partner through implementation',actions:'Defines layout rules, tests representative content and widths, and prioritizes what remains visible or actionable.',evidence:'Synthesized from O*NET cross-device usability scope and responsive UI practice · Validate with viewport and device audits'},
    {name:'Component and design-system thinking',status:'Synthesized',definition:'Create and apply reusable interface patterns while preserving the context, flexibility, and limits that make them useful.',triggers:'Repeated local solution · Pattern drift · New component request · Existing component does not fit the task',workflows:'Extend and govern the design system · Craft the core interaction and visual system',actions:'Chooses the right abstraction, documents states and usage, and challenges reuse when it creates a worse experience.',evidence:'Synthesized from GOV.UK strategic design skills and role workflows · Validate through a pattern review'},
    {name:'Accessibility and inclusive design',status:'Synthesized',definition:'Identify and reduce barriers in the interface so people with different abilities, devices, and ways of interacting can complete the task.',triggers:'Accessibility concern · New interaction pattern · Keyboard, focus, contrast, motion, or target-size risk',workflows:'Craft the core interaction and visual system · Repair a broken or confusing interface',actions:'Checks perceivability and operability, proposes inclusive alternatives, and combines automated checks with human evaluation.',evidence:'Grounded in WCAG 2.2 and GOV.UK designing-for-everyone guidance · Validate with accessibility review and assistive-technology testing'},
    {name:'Prototyping and interaction craft',status:'Synthesized',definition:'Make an interface behavior tangible at the fidelity needed to answer the current design question.',triggers:'Competing interpretations · Motion or transition is part of meaning · Implementation risk is high',workflows:'Craft the core interaction and visual system · Resolve a pattern or constraint conflict',actions:'Selects the cheapest credible prototype, demonstrates behavior, and iterates based on feedback and feasibility.',evidence:'Synthesized from iterative design guidance and interface practice · Validate with a work sample or prototype critique'},
    {name:'Design QA and implementation partnership',status:'Synthesized',definition:'Protect the intended experience as a design moves into code by making differences, constraints, and corrections visible.',triggers:'Build differs from design · Release review · New technical constraint · Pattern implementation is ambiguous',workflows:'Partner through implementation · Repair a broken or confusing interface',actions:'Reviews real builds, explains intent and priority, negotiates tradeoffs, and records follow-through for important gaps.',evidence:'Synthesized from O*NET collaboration/testing tasks and cross-functional design practice · Validate through an implementation audit'}
  ],
  'ai-orchestrator':[
    {name:'Agent workflow architecture',status:'Synthesized',definition:'Turn a goal into a bounded workflow or agent system with clear ownership, state, tools, and stopping conditions.',triggers:'Open-ended task · Multiple specialist capabilities · Unclear success boundary',workflows:'Frame the system goal and boundary · Compose the agent and tool system',actions:'Chooses the simplest viable pattern, maps control flow, and makes failure paths explicit.',evidence:'Synthesized from agent architecture guidance · Validate with an architecture review'},
    {name:'Work graph orchestration',status:'Synthesized',definition:'Supervise dependency-aware work across multiple executors by maintaining authoritative WorkNodes, Dispatches, Gates, evidence, and dispositions without becoming the execution runtime.',triggers:'Substantial outcome spans multiple issues, branches, PRs, agents, or runtimes · Parallel work has dependency or collision risk · Delegated work must be supervised or recovered',workflows:'Compose the agent and tool system · Operate and improve the system · Recover a failed or unsafe run',actions:'Builds the smallest useful work graph, distinguishes work from execution attempts, dispatches only ready collision-safe nodes, verifies completion through explicit evidence, and reconciles retries or recovery to durable checkpoints.',evidence:'Working synthesis from CW-44 comparison of supervised DAG, issue-to-PR, isolation, lifecycle, recovery, and governance patterns · Validate with real supervised dispatch and recovery cases'},
    {name:'Task decomposition and routing',status:'Synthesized',definition:'Break complex work into the right subtasks and direct each part to the best specialist, model, or tool.',triggers:'Task has distinct request types · Work exceeds one specialist’s context · Cost or latency varies by case',workflows:'Compose the agent and tool system · Operate and improve the system',actions:'Defines routing criteria, assigns specialist ownership, and checks that handoffs preserve needed context.',evidence:'Synthesized from routing and orchestrator-worker patterns · Validate with routing evals'},
    {name:'Tool and context design',status:'Synthesized',definition:'Give agents clear, constrained interfaces to the information and actions they need.',triggers:'Agent guesses at a tool · Context is missing or oversized · Side effect needs a boundary',workflows:'Compose the agent and tool system · Recover a failed or unsafe run',actions:'Documents tool contracts, limits permissions, curates context, and separates information from side effects.',evidence:'Synthesized from tool-interface and MCP guidance · Validate through tool-use tests'},
    {name:'Risk, guardrails, and human oversight',status:'Synthesized',definition:'Place policy, approval, and human-review boundaries around autonomous behavior and consequential actions.',triggers:'Sensitive data or action · High-consequence decision · Agent requests an exception or approval',workflows:'Set approval and guardrail points · Coordinate stakeholders and governance',actions:'Maps risks, defines pause points, tests guardrails, and assigns human accountability.',evidence:'Synthesized with NIST AI RMF and agent guardrail guidance · Validate with a risk review'},
    {name:'Failure recovery and operational judgment',status:'Synthesized',definition:'Contain, understand, and correct a failed or unsafe run without losing the ability to learn from it.',triggers:'Run loops or stalls · Tool returns bad state · Model or provider behavior changes',workflows:'Recover a failed or unsafe run · Adapt after a model or tool change',actions:'Stops side effects, reconstructs the trace, chooses rollback or correction, and records the learning.',evidence:'Hypothesis from agent operations patterns · Validate with incident simulations'},
    {name:'Cross-functional systems communication',status:'Synthesized',definition:'Make agent behavior, tradeoffs, ownership, and uncertainty legible to technical, domain, security, and product partners.',triggers:'New system crosses team boundaries · Governance review · Domain expert disputes an output',workflows:'Coordinate stakeholders and governance · Frame the system goal and boundary',actions:'Explains the system in shared language, surfaces unresolved decisions, and keeps ownership visible.',evidence:'Synthesized from governance and orchestration needs · Validate with a system walkthrough'},
    {name:'Multi-perspective skill synthesis',status:'Synthesized',definition:'Combine bounded perspectives from multiple personas into one reusable capability without flattening their differences or duplicating existing skills.',triggers:'A capability spans several roles · One perspective leaves a quality gap · A proposed skill could be either a new capability or a composition of existing ones',workflows:'Coordinate perspectives and form the skill · Formalize and integrate the reusable skill',actions:'Selects relevant personas, compares their workflows and quality signals, resolves overlap, and records what is shared, role-specific, and still uncertain.',evidence:'Working synthesis informed by multi-persona orchestration, information architecture, and skill-formation practice · Validate through cross-persona review and later reuse'}
  ],
  'ux-senior':[
    {name:'Problem framing and systems thinking',status:'Synthesized',definition:'Turn an ambiguous product request into a shared problem, outcome, and decision frame.',triggers:'Ambiguous brief · Conflicting stakeholder goals · Unclear decision owner',workflows:'Frame the right product problem · Reconcile conflicting evidence',actions:'Names outcomes, assumptions, constraints, and what would change the call.',evidence:'Synthesized from role workflows · Validate with a framing review'},
    {name:'Interaction design and information architecture',status:'Synthesized',definition:'Shape usable flows, states, and structures that help people find and complete what matters.',triggers:'Unclear user path · New product requirement · Repeated usability issue',workflows:'Design and validate a solution · Steward the experience system',actions:'Maps states, tests critical paths, and makes information findable.',evidence:'Synthesized from role workflows · Validate through portfolio review'},
    {name:'Prototyping and usability evaluation',status:'Synthesized',definition:'Use the lightest realistic representation to learn whether a direction works before delivery.',triggers:'Riskiest assumption is unclear · Solution has competing interpretations · Delivery cost is rising',workflows:'Design and validate a solution',actions:'Chooses fidelity to match the question, observes representative users, and changes the design from evidence.',evidence:'Synthesized from role workflows · Validate with a work sample'},
    {name:'Facilitation and cross-functional alignment',status:'Synthesized',definition:'Create the conditions for a group to make a clear decision across disciplines and constraints.',triggers:'Stakeholder disagreement · Cross-functional handoff · Decision with missing voices',workflows:'Frame the right product problem · Carry a decision into delivery · Steward the experience system',actions:'Chooses the right activity, surfaces disagreement, and closes with owners and next steps.',evidence:'Synthesized from role workflows · Validate with a live workshop'},
    {name:'Accessibility and inclusive design',status:'Synthesized',definition:'Protect inclusive quality by recognizing exclusion risks and changing the experience or implementation.',triggers:'Accessibility concern · Late implementation constraint · Risk of excluding a user group',workflows:'Design and validate a solution · Recover a compromised experience',actions:'Spots barriers, proposes alternatives, and checks the built experience against inclusive requirements.',evidence:'Synthesized with W3C guidance · Validate through an accessibility critique'},
    {name:'Design-system stewardship',status:'Synthesized',definition:'Improve shared patterns so consistency, quality, and reuse support the actual user need.',triggers:'Repeated local fix · Pattern drift · Team needs guidance for a new state',workflows:'Steward the experience system',actions:'Contributes patterns, critiques reuse decisions, and records examples with their limits.',evidence:'Synthesized from role workflows · Validate with a system review'},
    {name:'Decision communication and rationale documentation',status:'Synthesized',definition:'Make the reasoning, tradeoffs, and uncertainty behind a design decision durable as work moves forward.',triggers:'Handoff strips away context · Decision is revisited · Evidence and constraints disagree',workflows:'Carry a decision into delivery · Reconcile conflicting evidence',actions:'Explains states and tradeoffs, names open questions, and records what would change the call.',evidence:'Synthesized from role workflows · Validate through a rationale review'}
  ],
  'job-seeker':[
    {name:'Role targeting and search prioritization',status:'Synthesized',definition:'Choose a bounded search direction by comparing desired work, constraints, evidence, and opportunity.',triggers:'Too many plausible roles · Search activity is unfocused · Constraints change',workflows:'Define the target search · Recover after silence or rejection · Reposition after repeated mismatch',actions:'Names a primary target, adjacent options, non-negotiables, and a rule for deciding what to pursue next.',evidence:'Synthesized from career-development research · Validate against the person’s actual search decisions'},
    {name:'Evidence inventory and achievement framing',status:'Synthesized',definition:'Turn experience, outcomes, artifacts, decisions, and learning into specific evidence that can travel across materials and conversations.',triggers:'Resume feels generic · Strong work is hard to remember · Claim lacks proof',workflows:'Build the evidence inventory · Tailor an application packet · Reposition after repeated mismatch',actions:'Collects source material, separates contribution from activity, and records confidence and missing proof.',evidence:'Synthesized from application-writing and career-counseling research · Validate with source documents and examples'},
    {name:'Professional writing and voice preservation',status:'Synthesized',definition:'Communicate fit and contribution clearly while keeping the language truthful and recognizably the candidate’s.',triggers:'Draft sounds manufactured · Cover letter repeats the resume · Feedback asks for more personality',workflows:'Tailor an application packet · Recover after silence or rejection',actions:'Chooses relevant evidence, edits for clarity, and checks that language remains specific and authentic.',evidence:'Synthesized from technical-writing and career-readiness research · Validate with candidate review'},
    {name:'Career self-development and networking',status:'Synthesized',definition:'Use reflection, relationships, and practice to build capability and access during a search.',triggers:'Role requires an unfamiliar capability · Search is isolated · Conversation could unlock learning',workflows:'Research a target company or team · Prepare outreach and interview conversations',actions:'Identifies a learning goal, asks purposeful questions, and turns conversations into next steps.',evidence:'Synthesized from NACE competencies and career counselor tasks · Validate with search outcomes'},
    {name:'Critical reading of role requirements',status:'Synthesized',definition:'Interpret a role description as a set of outcomes, signals, constraints, and unknowns rather than a keyword list.',triggers:'Job description is inflated · Requirements conflict · Level is unclear',workflows:'Define the target search · Analyze a role and build the evidence map · Tailor an application packet',actions:'Separates must-have signals from preferences and maps each important claim to evidence or a question.',evidence:'Synthesis informed by ATS and hiring-side sources · Validate against the actual employer process'},
    {name:'Application tool literacy',status:'Synthesized',definition:'Use search, document, ATS, portfolio, and tracking tools without letting the tools distort the search or story.',triggers:'Formatting may not parse · Work is duplicated · Application status is unclear',workflows:'Build the evidence inventory · Tailor an application packet · Track and learn from the search',actions:'Uses standard structure, preserves source material, records versions, and treats tools as aids rather than authorities.',evidence:'Synthesized from ATS guidance · Validate with a real submission or parser check'}
  ],
  'career-strategist':[
    {name:'Career assessment and goal framing',status:'Synthesized',definition:'Elicit goals, history, interests, barriers, and preferences so the search starts from the person’s situation.',triggers:'Client asks for a title too early · Goals conflict · Constraints are implicit',workflows:'Intake and scope the search · Support a high-stakes transition',actions:'Uses structured questions, reflects back the frame, and records what is known, assumed, and still open.',evidence:'Synthesized from O*NET career counselor tasks · Validate with observed intake practice'},
    {name:'Role-family and market interpretation',status:'Synthesized',definition:'Compare adjacent occupations, employers, and opportunity signals to make options realistic and legible.',triggers:'Role titles vary by industry · Market language is unfamiliar · Client has transferable experience',workflows:'Map target role families and market · Shape positioning and search channels',actions:'Compares work, scope, requirements, and constraints across options instead of matching titles alone.',evidence:'Synthesized from occupational information and coaching practice · Validate against current market sources'},
    {name:'Search sequencing and prioritization',status:'Synthesized',definition:'Order research, networking, applications, and practice so each activity produces useful progress or learning, and keep discovered opportunities durable through the job ledger.',triggers:'Many possible next steps · Activity rises without results · Deadline or urgency changes · The same jobs resurface as if new',workflows:'Shape positioning and search channels · Review materials and next actions · Map target role families and market',actions:'Defines a small next experiment, its signal, and the condition for changing course; checks the durable job ledger before treating a posting as new; updates last_seen and disposition for known roles.',evidence:'Synthesized from career-development practice plus issue #90 ledger contract · Validate through follow-up outcomes and repeated-search behavior'},
    {name:'Coaching and confidence calibration',status:'Synthesized',definition:'Support action without overstating readiness, fit, or certainty.',triggers:'Confidence collapses after rejection · Materials are polished but ungrounded · Client avoids a stretch',workflows:'Intake and scope the search · Support a high-stakes transition',actions:'Separates emotional state, evidence, and decision; then chooses an appropriately sized next step.',evidence:'Working synthesis · Validate with supervised coaching or reflective interviews'},
    {name:'Evidence-led feedback',status:'Synthesized',definition:'Give feedback that points to observable evidence, consequence, and a specific revision.',triggers:'Advice is generic · Client receives conflicting edits · A claim lacks support',workflows:'Review materials and next actions · Shape positioning and search channels',actions:'Names what a reader can see, what remains unclear, and what evidence would change the recommendation.',evidence:'Synthesized from NACE competencies and counselor tasks · Validate with recorded reviews'},
    {name:'Follow-up and plan revision',status:'Synthesized',definition:'Use applications, conversations, and changed circumstances to update the search rather than repeating the same plan.',triggers:'Repeated mismatch · New information from an employer · Strategy stops producing learning',workflows:'Review materials and next actions · Support a high-stakes transition',actions:'Revisits assumptions, preserves what was learned, and changes the plan at the smallest useful level.',evidence:'Synthesized from O*NET follow-up tasks · Validate through longitudinal cases'}
  ],
  'role-calibrator':[
    {name:'Role analysis and success modeling',status:'Synthesized',definition:'Translate a role brief into outcomes, capabilities, constraints, and observable signs of success.',triggers:'Job description mixes preferences and requirements · Level is unclear · Panel lacks a shared frame',workflows:'Define role success · Align the hiring panel',actions:'Separates the work to be done from copied language and names what evidence would matter.',evidence:'Synthesized from O*NET HR specialist tasks · Validate with the actual hiring team'},
    {name:'Evidence calibration and structured screening',status:'Synthesized',definition:'Compare candidate evidence against the role using consistent questions and a visible standard.',triggers:'Application volume is high · Familiarity is influencing judgment · ATS match is ambiguous',workflows:'Screen candidate evidence · Reconcile an ambiguous candidate',actions:'Reviews comparable evidence, records uncertainty, and avoids treating parsing or polish as proof of capability.',evidence:'Synthesized from HR and ATS sources · Validate with screening samples and reviewer calibration'},
    {name:'Interview design and evaluation',status:'Synthesized',definition:'Create interview prompts and evaluation criteria that reveal relevant decisions, behaviors, and outcomes.',triggers:'Interviews are inconsistent · Panel asks the same shallow question · Evidence is hard to compare',workflows:'Run a structured interview · Align the hiring panel',actions:'Connects questions to role outcomes and records evidence separately from impressions.',evidence:'Working synthesis informed by recruiting practice · Validate with interview debriefs'},
    {name:'Fairness-aware decision making',status:'Synthesized',definition:'Notice where process design, irrelevant signals, or inconsistent evaluation can distort a hiring decision.',triggers:'Panel disagreement · Unstructured preference enters the decision · Candidate experience is at risk',workflows:'Screen candidate evidence · Align the hiring panel · Close the hiring decision',actions:'Makes criteria explicit, checks comparability, and keeps uncertainty visible rather than rationalizing it away.',evidence:'Synthesized with Greenhouse candidate-experience guidance · Validate with process review'},
    {name:'Cross-functional hiring alignment',status:'Synthesized',definition:'Help recruiters, managers, and interviewers share the same role frame, evidence standard, and decision rights.',triggers:'Panel uses different level language · Feedback is fragmented · Decision owner is unclear',workflows:'Define role success · Align the hiring panel',actions:'Surfaces differences, resolves criteria, and records what each interviewer owns.',evidence:'Synthesized from HR specialist work activities · Validate with panel artifacts'},
    {name:'Candidate communication',status:'Synthesized',definition:'Communicate process, status, and next steps in a way that preserves clarity and respect.',triggers:'Process changes · Candidate is waiting · Decision requires follow-up',workflows:'Close the hiring decision · Reconcile an ambiguous candidate',actions:'Shares useful status, avoids avoidable ambiguity, and keeps the message consistent with the actual process.',evidence:'Synthesized with candidate-centric ATS guidance · Validate through candidate feedback'}
  ],
  'application-editor':[
    {name:'Requirement-to-evidence mapping',status:'Synthesized',definition:'Connect a role’s important requirements to truthful examples, outcomes, and confidence levels.',triggers:'Job description is dense · Claim has no proof · Candidate has transferable experience',workflows:'Translate role brief into an evidence map · Reconcile truthful gaps',actions:'Builds a source-grounded context brief and claim ledger; maps role requirements to original passages, supported wording, uncertainty, and review status.',evidence:'Synthesized from ATS, technical-writing, and career-counseling sources · Validate against source material'},
    {name:'Information architecture and document hierarchy',status:'Synthesized',definition:'Organize application content so both parsers and people can find the intended signal quickly.',triggers:'Document is hard to scan · Sections are inconsistent · Formatting is doing too much work',workflows:'Draft resume and application materials · Run the ATS pass · Edit for human reading',actions:'Uses standard structure, meaningful headings, and hierarchy that supports the reader’s decision path.',evidence:'Synthesized from BLS and ATS guidance · Validate with human review and parser testing'},
    {name:'Persuasive professional writing',status:'Synthesized',definition:'Make contribution, relevance, and credibility clear without inflating the underlying experience.',triggers:'Bullets list activity without impact · Cover letter adds repetition · Reader cannot see fit',workflows:'Draft resume and application materials · Edit for human reading · Prepare a cover letter or portfolio narrative',actions:'Trials a summary and two role entries, restores relevant method and scope, removes repeated claims, and checks fit and contribution with a fresh reader.',evidence:'Synthesized from technical-writing and career-readiness sources · Validate with reader comprehension'},
    {name:'ATS-aware formatting and terminology',status:'Synthesized',definition:'Improve machine readability and terminology alignment while preserving truthful meaning and usable structure.',triggers:'Parser may misread dates or titles · Role terms are absent · Graphic layout hides content · Resume chronology or date precision is unclear',workflows:'Run the ATS pass · Draft resume and application materials · Reconcile a truthful application packet',actions:'Checks the actual final document for role dates, reverse chronology, engagement identity, and ambiguity before reviewing extraction and supported terminology; reports which checks actually ran.',evidence:'Synthesized from Indeed, Workday, and Greenhouse ATS guidance plus an observed chronology failure in a draft packet · Validate with the target employer when possible'},
    {name:'Voice preservation and ethical editing',status:'Synthesized',definition:'Improve clarity and relevance without replacing the candidate’s identity, judgment, or truth.',triggers:'Draft sounds generic · AI-generated language is overconfident · Unsupported achievement appears',workflows:'Edit for human reading · Reconcile truthful gaps',actions:'Compares each meaningful edit with its source, preserves contribution and metric meaning, and asks the real author only about consequential unresolved interpretation.',evidence:'Working synthesis informed by integrity requirements · Validate with candidate sign-off'},
    {name:'Visual communication for application materials',status:'Synthesized',definition:'Use hierarchy, density, typography, and portfolio composition to support a role-appropriate reading path.',triggers:'Document feels crowded · Portfolio has weak sequence · Aesthetic treatment competes with evidence',workflows:'Edit for human reading · Prepare a cover letter or portfolio narrative',actions:'Calibrates visual choices to medium, industry, seniority, and the reader’s time.',evidence:'Synthesized with Camille Ortiz’s visual-judgment capability · Validate through visual and content review'}
  ],
  'outreach-interview-coach':[
    {name:'Targeted outreach and networking',status:'Synthesized',definition:'Choose a recipient, purpose, and useful request so outreach creates a credible next step.',triggers:'Message is generic · Recipient is unclear · Candidate asks for too much',workflows:'Choose an outreach path · Write a targeted message · Follow up and reflect',actions:'Uses relevant context, a bounded ask, and a respectful path to decline or respond.',evidence:'Synthesized from career self-development and communication competencies · Validate with message outcomes'},
    {name:'Evidence-led interview storytelling',status:'Synthesized',definition:'Explain decisions, contribution, outcomes, and learning through specific, adaptable examples.',triggers:'Answer stays abstract · Role requires scope evidence · Follow-up question exposes a gap',workflows:'Prepare evidence stories · Rehearse an interview · Recover after a difficult interview',actions:'Selects an example that fits the question, names the candidate’s contribution, and avoids memorized overclaiming.',evidence:'Synthesized from career counselor interview-skills tasks · Validate with mock interview observation'},
    {name:'Active listening and question design',status:'Synthesized',definition:'Use the conversation to understand the role, team, expectations, and next decision—not just to perform.',triggers:'Conversation is one-sided · Information is missing · Candidate needs to assess fit',workflows:'Choose an outreach path · Rehearse an interview · Follow up and reflect',actions:'Asks questions tied to role outcomes, listens for evidence, and adjusts the next question to what was said.',evidence:'Synthesized from communication and critical-thinking competencies · Validate through conversation review'},
    {name:'Adaptive rehearsal',status:'Synthesized',definition:'Practice the reasoning and evidence behind an answer so the candidate can respond when conditions change.',triggers:'Candidate memorizes scripts · Interview format is uncertain · Follow-ups derail the answer',workflows:'Prepare evidence stories · Rehearse an interview',actions:'Varies prompts, time limits, audience, and interruptions while preserving the underlying evidence.',evidence:'Working synthesis · Validate with repeated mock interviews'},
    {name:'Professional follow-up',status:'Synthesized',definition:'Carry the conversation forward with a timely, specific, and accurate follow-up.',triggers:'Interview ends with open questions · New information changes the message · Next step is unclear',workflows:'Write a targeted message · Follow up and reflect',actions:'References the actual conversation, clarifies next steps, and avoids generic gratitude language.',evidence:'Synthesized from career communication practice · Validate against recipient response'},
    {name:'Reflection and learning capture',status:'Synthesized',definition:'Turn each conversation into a clearer search, stronger evidence, or a better next question.',triggers:'Conversation reveals a mismatch · Candidate receives rejection or silence · New role signal appears',workflows:'Follow up and reflect · Recover after a difficult interview',actions:'Records what was learned, what remains uncertain, and what to change before the next interaction.',evidence:'Synthesized from career self-development and follow-up practice · Validate longitudinally'}
  ],
  'knowledge-systems-architect':[
    {name:'Information architecture and concept modeling',status:'Synthesized',definition:'Model the kinds of things a system contains, the boundaries between them, and the relationships that help people find and use them.',triggers:'A new concept resembles several existing ones · Navigation feels harder to explain · Content or capability is difficult to place',workflows:'Frame the system’s concept model · Place a new concept in the architecture · Maintain the shared taxonomy and boundaries',actions:'Names the concept’s responsibility, compares it with neighboring objects, maps relationships and ownership, and tests whether the model supports retrieval and contribution.',evidence:'Synthesized from Information Architecture Institute and GOV.UK service-structure guidance · Validate through card sorts, tree tests, retrieval behavior, and contributor interviews'},
    {name:'Concept classification and boundary design',status:'Synthesized',definition:'Decide whether an addition is a new object, a relationship, a variation, or a future possibility, then define what it should and should not contain.',triggers:'A proposal could fit multiple spaces · A page is accumulating mixed responsibilities · Similar concepts are being duplicated',workflows:'Place a new concept in the architecture · Resolve an overlap or category conflict',actions:'Classifies the proposal by purpose and lifecycle, writes inclusion and exclusion rules, and records the closest alternatives considered.',evidence:'Working synthesis informed by IA taxonomy and systems-analysis practice · Validate through classification exercises and later retrieval success'},
    {name:'Taxonomy, labeling, and navigation',status:'Synthesized',definition:'Create labels, groupings, and routes that reflect how people expect to find and understand the system’s contents.',triggers:'People search using different language · A label requires explanation · Users open the wrong space or miss related material',workflows:'Frame the system’s concept model · Maintain the shared taxonomy and boundaries · Explain the architecture to contributors',actions:'Collects user language, tests candidate groupings and labels, checks cross-links and navigation, and keeps internal terminology from leaking into user-facing structure.',evidence:'Synthesized from IA practice and GOV.UK card-sorting guidance · Validate with card sorts, tree tests, search logs, and observed navigation'},
    {name:'Dependency mapping and change impact',status:'Synthesized',definition:'Trace how a structural or content change affects related personas, skills, playbooks, docs, decisions, and navigation.',triggers:'A high-reuse concept changes · A new space or relationship is introduced · A revision may make other records stale',workflows:'Coordinate cross-space updates · Reconcile drift after a change',actions:'Maps direct and indirect dependents, distinguishes required from optional updates, and creates a bounded reconciliation queue.',evidence:'Working synthesis informed by systems integration and change-management practice · Validate through impact reviews and reconciliation outcomes'},
    {name:'Decision communication and rationale documentation',status:'Synthesized',definition:'Make architectural choices understandable by recording context, alternatives, tradeoffs, consequences, and revision conditions.',triggers:'A boundary decision will be revisited · Contributors disagree about placement · A temporary exception risks becoming precedent',workflows:'Resolve an overlap or category conflict · Explain the architecture to contributors',actions:'Writes a concise decision record, separates evidence from assumptions, names ownership, and states what future evidence would change the choice.',evidence:'Synthesized from Architectural Decision Records practice · Validate by asking an uninvolved contributor to explain the decision'},
    {name:'Facilitation and cross-functional alignment',status:'Synthesized',definition:'Help people with different mental models reach a shared, evidence-informed understanding of how the system should be shaped.',triggers:'Product, design, engineering, and content use different terms · A new area has competing owners · The model affects several workflows',workflows:'Explain the architecture to contributors · Coordinate cross-space updates',actions:'Surfaces the decision to be made, brings the right examples and evidence, makes disagreement concrete, and closes with owners and next steps.',evidence:'Synthesized from cross-functional design and systems practice · Validate through workshop outcomes and follow-through'},
    {name:'Multi-perspective skill synthesis',status:'Synthesized',definition:'Combine bounded perspectives from multiple personas into one reusable capability without flattening their differences or duplicating existing skills.',triggers:'A capability spans several roles · One perspective leaves a quality gap · A proposed skill could be either a new capability or a composition of existing ones',workflows:'Coordinate perspectives and form the skill · Formalize and integrate the reusable skill',actions:'Selects relevant personas, compares their workflows and quality signals, resolves overlap, and records what is shared, role-specific, and still uncertain.',evidence:'Working synthesis informed by multi-persona orchestration, information architecture, and skill-formation practice · Validate through cross-persona review and later reuse'}
  ]
});
