window.PersonaLibraryDataFragments = window.PersonaLibraryDataFragments || {};
window.PersonaLibraryDataFragments.flowLibrary = window.PersonaLibraryDataFragments.flowLibrary || {};
Object.assign(window.PersonaLibraryDataFragments.flowLibrary, {
  'template-librarian':[
    {type:'foundational',title:'Steward the Template catalog',cadence:'Per catalog review / contribution',summary:'Keep Template identity, purpose, applicability, source evidence, status, lifecycle, and duplication boundaries trustworthy and findable.',activities:[['Inventory and classify Template records','Per catalog review','Findability','A useful starting artifact is hard to distinguish from a project output','Template catalog + source register (representative)'],['Verify source and provenance','Per contribution or source change','Trust','Repository existence is mistaken for artifact availability','Repository tree + path, entrypoint, and revision evidence (representative)'],['Check duplication and collection gaps','Per catalog review','Collection coherence','Near-duplicates multiply while useful categories remain absent','Catalog comparison + gap notes (representative)']]},
    {type:'foundational',title:'Route Template research and composition',cadence:'Per Template request',summary:'Classify the requested starting artifact, identify the relevant discipline, and hand substantive research or composition to the appropriate specialist.',activities:[['Classify artifact type and discipline','Per request','Correct ownership','The librarian is treated as a universal domain expert','Request brief + Template catalog (representative)'],['Select the smallest capable specialist','Per request','Domain quality','A handoff names a person without preserving the real context','Persona, Skill, and workflow map + handoff brief (representative)'],['Receive and review the specialist result','Per request','Boundary integrity','Examples, methodology, and project content are mixed together','Provenance note + artifact boundary review (representative)']]},
    {type:'supporting',title:'Promote and maintain reusable Templates',cadence:'Per reuse signal / source change',summary:'Distinguish local starters from reusable catalog entries, coordinate canonical placement, and keep metadata aligned with verified sources.',activities:[['Evaluate reuse and promotion evidence','Per candidate','Proportionate reuse','Every generated scaffold is promoted automatically','Reuse record + duplicate comparison (representative)'],['Coordinate canonical placement and source update','Per promotion or relocation','Provenance','Metadata points to an unstable or unverified artifact location','Canonical repository change + source record (representative)'],['Update lifecycle and relationship context','Per promotion or deprecation','Continuity','Downstream users see a stale status or ownership boundary','Catalog revision + affected relationship checklist (representative)']]},
    {type:'edge',title:'Reconcile Template lifecycle changes',cadence:'After a material Template change',summary:'Trace moves, deprecations, supersession, renames, source changes, and restructuring through related records and generated surfaces.',activities:[['Inspect changed identity, source, and status','After change','Coverage','Only the edited Template record is reviewed','Template diff + source evidence (representative)'],['Trace affected relationships and surfaces','After change','Consistency','Skills, Operating Packs, Playbooks, Docs, or Site output become stale','Dependency search + generated Site review (representative)'],['Escalate architecture questions to Mara','As needed','Boundary clarity','A lifecycle change silently changes the concept model','Architecture brief + Mara handoff (representative)']]}
  ],
  'ui-expert':[
    {type:'foundational',title:'Translate intent into interface structure',cadence:'Per project / feature',summary:'Turn a product goal and user task into a coherent information hierarchy, visual language, content model, and interaction frame.',activities:[['Study task, context, and content','Per project','Relevance','Briefs describe screens instead of the real situation','Research repository + analytics dashboard (representative)'],['Map hierarchy, composition, and critical path','Per project','Clarity and fit','Everything is given equal visual weight','Whiteboard or design workspace (representative)'],['Align on states and constraints','Per project','Completeness','Edge cases and implementation limits arrive late','Design specification + issue tracker (representative)']]},
    {type:'foundational',title:'Craft the core interaction and visual system',cadence:'Weekly / per sprint',summary:'Shape the contextual visual language, interface details, states, and responsive behavior that make the intended experience usable and expressive.',activities:[['Design the critical path and visual language','Weekly','Task confidence and fit','The happy path hides important decisions','Design workspace + component library (representative)'],['Prototype behavior and transitions','Per sprint','Learning speed','Static screens cannot answer the interaction question','Prototyping tool (representative)'],['Test with realistic content and widths','Per sprint','Robustness','Placeholder content makes weak layouts look healthy','Prototype preview + device or viewport tools (representative)']]},
    {type:'supporting',title:'Extend and govern the design system',cadence:'Weekly / monthly',summary:'Improve the shared language of components without allowing reuse to override the user’s actual need.',activities:[['Assess a pattern request','Weekly','Fit','Teams ask for components before clarifying the problem','Design-system backlog + issue tracker (representative)'],['Define states and usage guidance','Monthly','Consistency','A component is reused beyond its intended context','Component library + documentation (representative)'],['Review adoption and drift','Monthly','Quality at scale','Local variants quietly multiply','Design-system analytics or audit + design workspace (representative)']]},
    {type:'supporting',title:'Partner through implementation',cadence:'Daily / per release',summary:'Keep design intent, technical reality, and user impact aligned as the interface becomes a working product.',activities:[['Resolve feasibility questions','Daily','Shared understanding','Tradeoffs are found after a polished design is complete','Team chat + issue tracker + design workspace (representative)'],['Review the built experience','Per release','Fidelity','Small gaps accumulate across states and breakpoints','Staging build + browser/device tools (representative)'],['Prioritize and record corrections','Per release','Impact','Every visual difference competes equally for attention','Bug tracker + decision log (representative)']]},
    {type:'supporting',title:'Validate usability and accessibility',cadence:'Per sprint / per release',summary:'Use evidence and standards to check whether the interface works for real people across devices and ways of interacting.',activities:[['Run a focused usability check','Per sprint','Confidence','Feedback arrives after commitment','Research recruiting tool + session notes (representative)'],['Audit accessibility risks','Per release','Inclusive quality','Automated checks miss context and behavior','Accessibility checker + manual review checklist (representative)'],['Convert findings into design changes','Per release','Actionability','Findings become a report instead of a correction','Design workspace + issue tracker (representative)']]},
    {type:'edge',title:'Repair a broken or confusing interface',cadence:'As needed',summary:'Respond when users cannot complete a task, a release creates harm, or a pattern fails in context.',activities:[['Reconstruct the user impact','As needed','Severity','The loudest complaint is not always the highest-impact issue','Support tickets + analytics dashboard (representative)'],['Design the smallest safe correction','As needed','Recovery speed','A quick visual fix can break another state','Design workspace + component library (representative)'],['Verify and prevent recurrence','As needed','Learning','Temporary fixes become the new normal','Staging build + regression checklist (representative)']]},
    {type:'edge',title:'Resolve a pattern or constraint conflict',cadence:'As needed',summary:'Make a defensible call when consistency, accessibility, brand, content, or technical constraints pull in different directions.',activities:[['Separate principle from preference','As needed','Integrity','Taste is treated as a requirement','Design critique board + design principles (representative)'],['Prototype the tradeoff','As needed','Evidence','Teams debate without seeing the consequence','Prototype preview + device or accessibility tools (representative)'],['Record the exception and rationale','As needed','Traceability','A one-off becomes an unexplained precedent','Design-system documentation + decision log (representative)']]}
  ],
  'ai-orchestrator':[
    {type:'foundational',title:'Frame the system goal and boundary',cadence:'Per initiative',summary:'Turn an unqualified or open-ended opportunity into a bounded outcome, success measure, and stopping condition.',activities:[['Define success and stop condition','Per initiative','Usefulness and control','Teams jump to implementation before agreeing on the outcome','Product brief + evaluation plan (representative)'],['Choose workflow or agent pattern','Per initiative','Simplicity','Complexity is mistaken for capability','Architecture document + agent framework docs (representative)'],['Map owners and handoffs','Per initiative','Traceability','Responsibilities blur across specialists','Workflow diagram + agent registry (representative)']]},
    {type:'foundational',title:'Compose the agent and tool system',cadence:'Per initiative / iterative',summary:'Give models and specialist agents the roles, context, tools, and boundaries needed to work together.',activities:[['Define specialist roles','Per initiative','Separation of concerns','Agents overlap or contradict','Agent definitions + prompt version control (representative)'],['Design tool contracts and context','Iterative','Reliable action','Tools expose unclear or unsafe affordances','MCP or connector registry + tool schemas (representative)'],['Set approval and guardrail points','Iterative','Safe autonomy','Review arrives after side effects','Guardrail configuration + approval queue (representative)']]},
    {type:'supporting',title:'Coordinate evaluation and improvement',cadence:'Per run / per release',summary:'Frame the evaluation, send every run to Noor for conformance observation, and use the classified evidence to improve the system.',handoff:{to:'conformance-observer',required:true,trigger:'Every evaluated run, including controlled comparisons and runs after a prompt, model, Tool, or context change.',input:'Normalized run conditions, expected contract, result, and relevant trace or fallback evidence.',output:'Noor observation with result class, evidence status, confidence, severity, repeatability, owner, and next test.',onUnavailable:'Record access-gap or unknown and do not claim conformance; continue only with an explicitly bounded fallback.'},activities:[['Define evaluation scope and stopping condition','Per run or release','Validity','The run is judged without an expected contract','Evaluation brief + Noor handoff'],['Invoke Noor’s conformance observation','Per run','Evidence','Riley or the final answer stands in for independent observation','Normalized result + observation entry'],['Route the finding into improvement work','Per run or release','Actionability','A finding has no owner or next test','Change decision + follow-up case']]},
    {type:'supporting',title:'Operate and improve the system',cadence:'Daily / weekly',summary:'Govern durable orchestration state for every substantial Current Work workstream, supervise a minimal work graph when outcomes span multiple execution lanes, allow the selected operating route to execute directly, and monitor live behavior, cost, latency, and reliability.',activities:[['Resume and checkpoint substantial work','At material transition','Continuity','A new agent reconstructs the work from scratch','Current Work + linked Work Order when one exists, otherwise authoritative recovery artifact (representative)'],['Reconcile durable orchestration state','At creation, material reroute, cross-agent handoff, major blocker, or completion','Continuity','Execution changes but the durable route and next action do not','Current Work Operating Route + Parent Work ID when applicable'],['Supervise the active work graph','During multi-lane execution','Coherent progress','Several agents or branches proceed without one authoritative dependency and dispatch view','WorkGraph packet + live runtime/GitHub references'],['Monitor run health','Daily','Reliability','Signals are split across services','Observability dashboard + alerting (representative)'],['Tune prompts, models, or routes','Weekly','Performance','Local fixes create new regressions','Prompt registry + model configuration (representative)'],['Document a release','Per release','Traceability','Changes outlive their rationale','Change log + architecture document (representative)']]},
    {type:'supporting',title:'Coordinate stakeholders and governance',cadence:'Weekly / per milestone',summary:'Keep product, engineering, domain, security, and compliance partners aligned on how the system acts.',activities:[['Review risk and permissions','Per milestone','Accountability','Ownership is unclear across systems','Risk register + access policy (representative)'],['Explain system behavior','Weekly','Shared understanding','People trust or reject the system without enough context','System walkthrough + trace examples (representative)'],['Collect domain feedback','Weekly','Relevance','Experts enter too late to shape the workflow','Feedback board + issue tracker (representative)']]},
    {type:'edge',title:'Recover a failed or unsafe run',cadence:'As needed',summary:'Contain side effects, reconstruct what happened, and restore a safe path forward.',activities:[['Stop or contain side effects','As needed','Safety','The system continues while the team diagnoses it','Approval control + incident channel (representative)'],['Reconstruct the run','As needed','Fast understanding','Tool calls and handoffs are hard to replay','Trace viewer + run logs (representative)'],['Correct and record the learning','As needed','Accountability','Workarounds become permanent','Incident record + evaluation case (representative)']]},
    {type:'edge',title:'Adapt after a model or tool change',cadence:'As needed',summary:'Reassess the system when a dependency changes behavior, cost, policy, or availability.',activities:[['Detect behavior drift','As needed','Confidence','Small changes surface only in production','Evaluation dashboard + alerts (representative)'],['Re-route or roll back','As needed','Continuity','The fallback path is not ready','Release controls + provider configuration (representative)'],['Update the operating contract','As needed','Clarity','New limits are not shared with users or teams','Architecture document + change log (representative)']]}
  ],
  maya:[
    {type:'foundational',title:'Triage incoming work',cadence:'Daily',summary:'Sort requests, spot risk, and assign the next owner.',activities:[['Review queue','Daily','Visibility','Information is scattered'],['Assign owner','Daily','Clear ownership','Handoffs are easy to miss']]},
    {type:'foundational',title:'Monitor service quality',cadence:'Daily',summary:'Watch leading signals before customers feel the impact.',activities:[['Check leading signals','Daily','Early warning','Dashboards lag'],['Review exceptions','Daily','Consistency','Patterns are hard to compare']]},
    {type:'supporting',title:'Improve a broken process',cadence:'Weekly',summary:'Turn a recurring workaround into a better team practice.',activities:[['Capture workaround','Weekly','Practicality','Fixes stay local'],['Update playbook','Weekly','Reuse','Documentation goes stale']]},
    {type:'supporting',title:'Report operational health',cadence:'Weekly',summary:'Explain the state of service to the wider organization.',activities:[['Compile signal','Weekly','Accuracy','Metrics use different definitions'],['Explain variance','Weekly','Context','Numbers arrive without the why']]},
    {type:'edge',title:'Recover after escalation',cadence:'As needed',summary:'Rebuild the timeline and coordinate a fast response.',activities:[['Rebuild timeline','As needed','Fast context','History is split across tools'],['Close the loop','As needed','Confidence','Resolution is hard to verify']]},
    {type:'edge',title:'Cover a capacity gap',cadence:'As needed',summary:'Rebalance work when the team or demand changes suddenly.',activities:[['Rebalance queue','As needed','Fairness','Tradeoffs are implicit'],['Reset expectations','As needed','Trust','Updates take too long']]}
  ],
  tomas:[
    {type:'foundational',title:'Set up a useful first version',cadence:'Weekly',summary:'Choose a path, configure the essentials, and test value.',activities:[['Choose a path','Weekly','Momentum','Too many choices appear first'],['Test with a real task','Weekly','Relevance','Examples feel generic']]},
    {type:'foundational',title:'Learn from early users',cadence:'Weekly',summary:'Turn early reactions into the next product decision.',activities:[['Observe a user','Weekly','Signal','Feedback is sparse'],['Adjust the offer','Weekly','Speed','Learning competes with setup work']]},
    {type:'supporting',title:'Keep work moving solo',cadence:'Daily',summary:'Protect limited focus while switching between roles.',activities:[['Plan focus','Daily','Control','Every task feels urgent'],['Track open work','Daily','Visibility','Memory becomes the system']]},
    {type:'supporting',title:'Show progress to customers',cadence:'Weekly',summary:'Package enough proof to build confidence before the product is mature.',activities:[['Package proof','Weekly','Credibility','Evidence is scattered'],['Answer questions','Weekly','Clarity','Requests interrupt building']]},
    {type:'edge',title:'Undo a wrong turn',cadence:'Sometimes',summary:'Recognize a poor path and recover without losing momentum.',activities:[['Spot mismatch','Sometimes','Low risk','Errors feel expensive'],['Roll back','Sometimes','Reversibility','Undo paths are unclear']]},
    {type:'edge',title:'Respond when a customer is blocked',cadence:'As needed',summary:'Reproduce the issue, patch the path, and communicate clearly.',activities:[['Reproduce issue','As needed','Speed','Context is incomplete'],['Communicate update','As needed','Trust','Status work steals focus']]}
  ]
});
