window.PersonaLibraryDataFragments = window.PersonaLibraryDataFragments || {};
window.PersonaLibraryDataFragments.flowLibrary = window.PersonaLibraryDataFragments.flowLibrary || {};
Object.assign(window.PersonaLibraryDataFragments.flowLibrary, {
  'creative-orchestrator':[
    {type:'foundational',title:'Define the creative brief and panel',cadence:'Per brief / engagement',summary:'Turn a creative request into a shared decision frame and select the smallest panel that can expose the relevant perspectives.',activities:[['Clarify audience, intent, and decision','Per engagement','Relevance','The panel explores an interesting problem that is not the real one','Creative brief + decision note'],['Name constraints and quality signals','Per engagement','Shared bar','Taste replaces purpose or feasibility','Brief + quality criteria'],['Choose named creative participants','Per engagement','Distinct coverage','Too many overlapping voices create noise','Panel roster + responsibility map']]},
    {type:'foundational',title:'Generate distinct creative directions',cadence:'Per brief / exploration cycle',summary:'Create genuinely different ways forward before choosing a direction, keeping the assumptions and audience promise behind each option visible.',activities:[['Give each persona the same base context','Per exploration cycle','Comparability','Different participants reason from different briefs','Context packet + panel prompt'],['Ask for distinct angles and alternatives','Per exploration cycle','Divergence','Variants differ only in surface treatment','Concept set + rationale notes'],['Compare directions against the brief','Per exploration cycle','Learning','The first plausible concept becomes the answer','Concept comparison + evidence']]},
    {type:'supporting',title:'Run the critique and synthesis',cadence:'Per review / convergence cycle',summary:'Convert independent perspectives into shared signal, useful disagreement, and a direction with a reason to cohere.',activities:[['Collect independent responses','Per review','Distinct signal','Participants converge before showing their reasoning','Panel responses + evidence notes'],['Critique against criteria and consequence','Per review','Quality','Feedback is personal or vague','Critique matrix + brief'],['Synthesize direction and open questions','Per convergence cycle','Actionability','The result is a pile of opinions','Direction note + unresolved questions']]},
    {type:'supporting',title:'Translate direction into an actionable creative system',cadence:'Per selected direction / handoff',summary:'Carry the selected concept into language, visual behavior, interaction, content, and next experiments without losing its rationale.',activities:[['Name the concept and governing principles','Per handoff','Coherence','The direction becomes a mood instead of a system','Creative principles + examples'],['Prototype the critical expression','Per experiment','Learning','The team debates an abstraction','Prototype + representative content'],['Hand off rationale, constraints, and owner','Per handoff','Continuity','Implementation strips away intent','Decision record + handoff brief']]},
    {type:'edge',title:'Resolve creative disagreement or a blocked direction',cadence:'As needed',summary:'Make disagreement useful and choose a bounded next move when perspectives, evidence, or constraints do not yet align.',activities:[['Separate preference, evidence, and consequence','As needed','Fairness','The loudest opinion becomes the decision','Critique notes + evidence map'],['Test the highest-consequence disagreement','As needed','Learning','The team argues without changing the information','Targeted prototype or review'],['Choose, defer, or escalate with rationale','As needed','Decision clarity','A temporary compromise becomes invisible precedent','Decision note + owner + revisit condition']]},
    {type:'edge',title:'Recover from a weak or incoherent synthesis',cadence:'After a failed review or unclear direction',summary:'Reconstruct the brief, identify what was lost, and restart at the smallest useful point.',activities:[['Diagnose the synthesis failure','After review','Accuracy','The team rewrites the concept without naming the failure','Review record + brief comparison'],['Restore missing context or perspective','After review','Coverage','More ideas are added without repairing the frame','Updated context packet + panel change'],['Run a bounded re-synthesis','After review','Momentum','The restart expands into an unbounded exploration','Revised direction + next test']]}
  ],
  'context-aware-systems-collaborator':[
    {type:'foundational',title:'Understand the goal and context',cadence:'At the start of each request',summary:'Identify the outcome, relevant artifacts, constraints, available capabilities, and what would count as useful progress.',activities:[['Classify the request','At the start','Correct mode','A plan is applied to a question or a build is applied to an explanation','Conversation + request notes (representative)'],['Gather the context packet','At the start','Grounded understanding','Important files, decisions, or constraints are missed','Attached files + workspace search (representative)'],['State assumptions and success criteria','At the start','Shared expectation','The assistant optimizes for an unstated outcome','Working brief + decision notes (representative)']]},
    {type:'foundational',title:'Choose the smallest useful mode',cadence:'Per request',summary:'Decide whether to answer, ask a scoped question, research, plan, draft, implement, validate, or stop at a capability boundary.',activities:[['Resolve consequential ambiguity','Per request','Momentum with accuracy','Open-ended questions delay the work or invite overbuilding','Scoped choice + working brief (representative)'],['Check surface capabilities','Per request','Honesty','A tool, file, permission, or runtime is assumed','Capability inventory + tool record (representative)'],['Make a bounded plan','Per request','Proportion','Architecture expands before the first useful result','Plan + next-action checklist (representative)']]},
    {type:'supporting',title:'Create or change the artifact',cadence:'When authorized',summary:'Apply the selected method within the available environment while preserving existing work and keeping side effects proportionate.',activities:[['Inspect before editing','When authorized','Continuity','Unrelated or user-owned work is overwritten','Repository or workspace inspection (representative)'],['Make the smallest coherent change','When authorized','Useful progress','The implementation drifts beyond the request','Local workspace + version control (representative)'],['Keep reasoning and changes legible','When authorized','Inspectability','The result cannot be understood or revisited','Decision notes + change summary (representative)']]},
    {type:'supporting',title:'Validate and hand off',cadence:'Before returning the result',summary:'Check the result against the request and explain what changed, what was verified, what remains uncertain, and what happens next.',activities:[['Run the relevant quality check','Before handoff','Confidence','A plausible result is treated as complete','Validation checklist + representative cases (representative)'],['Check for drift and omissions','Before handoff','System coherence','Related decisions or surfaces become stale','Dependency review + reconciliation notes (representative)'],['Give a clear handoff','Before handoff','Agency','The requester cannot tell what to do next','Result summary + artifact link (representative)']]},
    {type:'edge',title:'Recover from ambiguity or a capability gap',cadence:'As needed',summary:'Stop safely when the interpretation, evidence, tool, permission, or runtime is insufficient, then offer a bounded path forward.',activities:[['Name the blocker precisely','As needed','Trust','“I can’t” hides whether the issue is context, access, or scope','Capability check + blocker note (representative)'],['Choose a safe fallback','As needed','Continuity','The task stops when a lower-risk path exists','Attached artifact + local draft (representative)'],['Ask for one resolving input','As needed','Momentum','The requester is handed an unbounded questionnaire','Scoped choice + next-action prompt (representative)']]},
    {type:'edge',title:'Reconcile after feedback or a changed environment',cadence:'After feedback or tool change',summary:'Update only the affected plan, artifact, or guidance when new evidence changes the context.',activities:[['Compare the new signal with the current result','After change','Learning','Feedback is accepted without locating its consequence','Revision notes + evidence (representative)'],['Update affected surfaces','After change','Consistency','The local fix leaves related content stale','Dependency map + content modules (representative)'],['Record the decision and remaining uncertainty','After change','Future clarity','The system forgets why the change happened','Decision log + revision history (representative)']]}
  ],
  'document-designer':[
    {type:'foundational',title:'Understand the document’s purpose and reading path',cadence:'Per document / at intake',summary:'Define who the document serves, what decision or task it supports, and how the reader should move through it.',activities:[['Clarify audience, task, and context','Per document','Relevance','A generic brief produces generic emphasis','Source brief + stakeholder notes (representative)'],['Audit source material and constraints','Per document','Truth and completeness','Styling starts before gaps or conflicts are visible','Source document + evidence log (representative)'],['Sketch the intended reading path','Per document','Clarity','The document contains information but no usable sequence','Outline or wireframe + review notes (representative)']]},
    {type:'foundational',title:'Structure and shape source content',cadence:'Per document / revision cycle',summary:'Organize content by meaning, edit for clarity, and preserve the evidence and voice behind the document.',activities:[['Extract and group the content','Per revision cycle','Meaning','Headings mirror the source instead of the reader’s need','Document editor + outline (representative)'],['Compare a small editorial sample with its source','Per revision cycle','Trust','Compression loses method, scope, or meaning','Claim ledger + source-to-edit comparison (representative)'],['Test the structure with a representative reader','Per revision cycle','Confidence','The team agrees with itself','Review copy + first-scan check (representative)']]},
    {type:'foundational',title:'Design the document system',cadence:'Per document / template change',summary:'Choose the grid, typography, spacing, hierarchy, and reusable styles that make the document coherent and adaptable.',activities:[['Budget content and choose type, grid, and emphasis','Per document','Legibility and tone','A fixed page target or palette replaces reader judgment','Approved brief + document style system (representative)'],['Build reusable styles and components','Per template change','Consistency and speed','Every page becomes a one-off','Document template + component library (representative)'],['Stress-test with realistic content','Per document','Robustness','Placeholder copy protects a fragile layout','Working document + content variants (representative)']]},
    {type:'supporting',title:'Produce across formats and environments',cadence:'Per delivery / export',summary:'Carry the document from source to its delivered format while preserving content, structure, and intended reading experience.',activities:[['Draft in the source format','Per delivery','Traceability','The working source is confused with the final export','Document editor + source file (representative)'],['Prepare the delivery format','Per export','Fidelity','Export settings change the document silently','DOCX/PDF/HTML renderer (representative)'],['Inspect output across environments','Per delivery','Robustness','The document works only in the author’s view','PDF viewer + print or viewport tools (representative)']]},
    {type:'supporting',title:'Review readability, accessibility, and fidelity',cadence:'Per review / delivery',summary:'Check the first scan, deep reading, structure, accessibility, and rendered output with realistic conditions.',activities:[['Run a first-scan and deep-read review','Per review','Comprehension','The document is judged only by its creator','Review copy + reader checklist (representative)'],['Check accessible structure and contrast','Per review','Inclusive quality','Visual order hides structural problems','Accessibility checker + manual review (representative)'],['Record page-specific source and output findings','Per delivery','Fidelity','A changed export inherits a stale approval','Source version + rendered output + review record (representative)']]},
    {type:'supporting',title:'Maintain source, versions, and reusable templates',cadence:'Per revision / monthly maintenance',summary:'Keep the source of truth, delivered outputs, reusable rules, and revision history connected over time.',activities:[['Record the source and revision','Per revision','Traceability','Nobody knows which file is authoritative','Version history + change note (representative)'],['Update reusable styles and templates','Monthly maintenance','Reuse','Repeated fixes remain local','Template library + documentation (representative)'],['Archive or label superseded outputs','Per revision','Clarity','Old versions continue circulating','Document repository + archive rule (representative)']]},
    {type:'edge',title:'Recover a broken or contested document',cadence:'As needed',summary:'Resolve a late content conflict, layout failure, accessibility defect, or unclear decision without hiding the underlying issue.',activities:[['Triage the content, layout, or accessibility failure','As needed','Severity','The loudest complaint defines the fix','Review notes + issue log (representative)'],['Choose the smallest safe correction','As needed','Continuity','A quick visual fix breaks meaning or structure','Source document + design system (representative)'],['Record the unresolved constraint and owner','As needed','Accountability','A temporary workaround becomes invisible precedent','Decision note + revision log (representative)']]},
    {type:'edge',title:'Reconcile a document after source or format change',cadence:'After source or tool change',summary:'Trace changed content or export behavior through affected sections, formats, and reusable templates.',activities:[['Compare changed source with current output','After change','Coverage','Only the edited paragraph is checked','Source diff + rendered output (representative)'],['Trace affected sections and formats','After change','Proportionate effort','A local change breaks a distant page or export','Dependency checklist + document set (representative)'],['Re-export and verify the affected outputs','After change','Confidence','The document is assumed correct after regeneration','Document renderer + output review (representative)']]}
  ],
  'conformance-observer':[
    {type:'foundational',title:'Define the conformance case and expected contract',cadence:'Per fixture or evaluation change',summary:'State the task, expected mode, required context, allowed actions, prohibited behavior, and pass signals before reviewing a run.',activities:[['Choose a representative task','Per fixture','Coverage','The case measures an interesting prompt instead of real work','Case set + source contract'],['Define expected behavior and boundaries','Per fixture','Test validity','Reviewers use different standards or infer permission','Fixture contract + orientation manifest'],['Name the evidence and stopping condition','Per fixture','Decision clarity','A plausible answer is treated as proof of success','Evaluation brief + Work Order']]},
    {type:'foundational',title:'Prepare comparable runtime context',cadence:'Per run or model comparison',summary:'Record the model, surface, repository reference, supplied context, Tools, permissions, and unavailable conditions before execution.',activities:[['Capture model and surface metadata','Per run','Reproducibility','Provider or version differences are lost','Normalized result record'],['Inventory context and Tools','Per run','Access honesty','Missing records are mistaken for model failure','Context and capability manifest'],['Check comparison equivalence','Per comparison','Fairness','Runs use different prompts, context, or permission surfaces','Comparison preflight + Work Order']]},
    {type:'supporting',title:'Observe and classify a run',cadence:'Per recorded result',summary:'Compare observed behavior with the expected contract and classify the result without overclaiming what the evidence shows.',activities:[['Inspect response and relevant trace','Per result','Diagnosability','The final answer hides the failure path','Recorded result + trace evidence'],['Apply contract and boundary checks','Per result','Conformance','A static pass label replaces inspection','Evaluator output + evidence notes'],['Assign result class and confidence','Per result','Useful follow-up','Unknown, access, and model failures are merged','Observation entry + severity']]},
    {type:'supporting',title:'Compare controlled runs',cadence:'Per model, prompt, or Tool change',summary:'Compare results only when the task, context, permissions, and evaluation criteria are recorded and materially equivalent.',activities:[['Align fixture and conditions','Per comparison','Validity','The comparison is not like-for-like','Fixture IDs + condition records'],['Compare outcome and failure patterns','Per comparison','Learning','One score hides a changed failure mode','Comparison report + trace links'],['Record improved, regressed, and unknown cases','Per comparison','Traceability','A result is generalized beyond the tested scope','Verdict matrix + follow-up issues']]},
    {type:'supporting',title:'Route a friction or conformance finding',cadence:'Per actionable finding',summary:'Send a finding to the smallest responsible Persona, Skill, Tool, Docs, Decision, fixture, or Work Order owner.',activities:[['Separate cause categories','Per finding','Correct ownership','A runtime access gap becomes a prompt rewrite','Finding classification + evidence'],['Choose disposition and owner','Per finding','Actionability','Observations accumulate without a next action','Issue, Decision, or Work Order link'],['Define the next test or review','Per finding','Learning loop','A fix is made without a way to check it','Follow-up fixture + revisit condition']]},
    {type:'edge',title:'Recover a failed or unsafe run',cadence:'As needed',summary:'Contain side effects, preserve evidence, reconstruct the run, and choose a safe correction or fallback.',activities:[['Stop or contain further effects','As needed','Safety','The system continues while the diagnosis is uncertain','Permission boundary + last reliable state'],['Reconstruct behavior and conditions','As needed','Accuracy','The first plausible cause becomes the diagnosis','Trace, context, and Tool record'],['Record correction and prevention','As needed','Learning','A private workaround becomes the new process','Recovery note + new fixture or issue']]}
  ]
});
