const countFunctionDefinitions = (html, name) => (html.match(new RegExp(`function\\s+${name}\\s*\\(`, 'g')) || []).length;

export async function validateGeneratedOutputs(context) {
  const { files, routeSources, canvasModules, root } = context;
  const freshnessPairs = [
    ['librarySource', 'libraryOutput', 'Generated dist/data/library-data.js is stale; run build-library.mjs'],
    ['orientationSource', 'orientationOutput', 'Generated dist/data/site-orientation.json is stale; run build-library.mjs'],
    ['modelSource', 'modelOutput', 'Generated dist/data/library-model.js is stale; run build-library.mjs'],
    ['uiSource', 'uiOutput', 'Generated dist/js/library-ui.js is stale; run build-library.mjs'],
    ['stateSource', 'stateOutput', 'Generated dist/js/library-state.js is stale; run build-library.mjs'],
    ['templatePreviewSource', 'templatePreviewOutput', 'Generated dist/js/template-preview.js is stale; run build-library.mjs']
  ];
  for (const [sourceKey, outputKey, message] of freshnessPairs) if (files[sourceKey] !== files[outputKey]) throw new Error(message);
  for (const [sourcePath, outputPath] of canvasModules) {
    const [moduleSource, moduleOutput] = await Promise.all([context.readFile(sourcePath), context.readFile(outputPath)]);
    if (moduleSource !== moduleOutput) throw new Error(`Generated ${outputPath} is stale; run build-library.mjs`);
  }
  for (const { outputPath, source, output } of routeSources.values()) if (source !== output) throw new Error(`Generated ${outputPath} is stale; run build-library.mjs`);

  const { page, skillsPage, templatesPage, templateViewerPage, jobSearchPage, playbooksPage, operatingPacksPage, prototypingPage, canvasPage, guidePage } = files;
  for (const [name, html] of [['library', page], ['skills', skillsPage]]) for (const script of ['data/library-data.js', 'data/library-model.js', 'js/library-ui.js', 'js/library-state.js']) if (!html.includes(`<script src="${script}"></script>`)) throw new Error(`${name} page is missing ${script}`);
  for (const [name, html] of [['templates', templatesPage], ['template-viewer', templateViewerPage]]) if (!html.includes('<script src="js/template-preview.js"></script>')) throw new Error(`${name} page is missing js/template-preview.js`);
  for (const html of [page, skillsPage, jobSearchPage, playbooksPage, operatingPacksPage, templatesPage]) if (!html.includes('playbooks.html')) throw new Error('Primary pages must link to the Playbooks space');
  for (const html of [page, skillsPage, jobSearchPage, playbooksPage, operatingPacksPage, templatesPage]) if (!html.includes('operating-packs.html')) throw new Error('Primary pages must link to the Operating Packs space');
  for (const html of [page, skillsPage, jobSearchPage, playbooksPage, operatingPacksPage, templatesPage]) if (!html.includes('templates.html')) throw new Error('Primary pages must link to the Templates space');
  if (!jobSearchPage.includes('An evidence-led job search system.') || !jobSearchPage.includes('Define target') || !jobSearchPage.includes('ATS quality') || !jobSearchPage.includes('Integrity quality') || !jobSearchPage.includes('Preflight before the council') || !jobSearchPage.includes('reverse chronological') || !jobSearchPage.includes('date consistency')) throw new Error('Job search page is missing its system summary or quality gates');
  if (!playbooksPage.includes('Playbooks compose the system.') || !playbooksPage.includes('Evidence-led job search') || !playbooksPage.includes('Bounded parallel implementation') || !playbooksPage.includes('compact handoff') || !playbooksPage.includes('<span>4 roles</span>') || playbooksPage.includes('<span>3 roles</span>') || !playbooksPage.includes('Shared state keeps the playbook coherent') || !playbooksPage.includes('Change control') || !playbooksPage.includes('conditional reconciliation gate')) throw new Error('Playbooks page is missing its mental model or current playbook');
  if (!operatingPacksPage.includes('Operating Packs keep the domain in view.') || !operatingPacksPage.includes('operatingPackCatalog') || !operatingPacksPage.includes('planned') || !operatingPacksPage.includes('AGENTS.md') || !operatingPacksPage.includes("grid.addEventListener('toggle'") || !operatingPacksPage.includes('}, true);') || !operatingPacksPage.includes("state.set({ selected: '' })")) throw new Error('Operating Packs page is missing its catalog, source boundary, or planned example');
  if (!templatesPage.includes('Find the right starting shape.') || !templatesPage.includes('templateCatalog') || !templatesPage.includes('category-filter') || !templatesPage.includes('status-filter') || !templatesPage.includes('source-filter') || !templatesPage.includes('preview-filter') || !templatesPage.includes('catalog-summary') || !templatesPage.includes('template-research') || !templatesPage.includes('relatedToolRecipes') || !templatesPage.includes("grid.addEventListener('toggle'")) throw new Error('Templates page is missing its normalized catalog, filters, relationships, or lifecycle boundary');
  if (!templatesPage.includes("id=\"' + escapeHtml(template.id)") || !templatesPage.includes('window.location.hash.slice(1)') || !templatesPage.includes("scrollIntoView({ block: 'start' })") || templatesPage.includes('<span id="template-design-system-web-app" aria-hidden="true"></span>') || !templatesPage.includes('Entrypoint unknown') || !templatesPage.includes('sourceState') || !templatesPage.includes('previewState') || !templatesPage.includes('data-source-state') || !templatesPage.includes('data-preview-state') || !templatesPage.includes('Inspect Template →') || !templatesPage.includes('pinned ')) throw new Error('Templates page is missing rendered fragment selection or planned entrypoint handling');
  if (!templateViewerPage.includes('decision-panel') || !templateViewerPage.includes('decision-state-grid') || !templateViewerPage.includes('evidenceState') || !templateViewerPage.includes('sourceState') || !templateViewerPage.includes('runtimeAccessState') || !templateViewerPage.includes('previewState') || !templateViewerPage.includes('previewRenderers') || !templateViewerPage.includes('No local view') || !templateViewerPage.includes('pinned ')) throw new Error('Template viewer is missing its explicit evidence states or preview registry');
  if (templateViewerPage.includes('</header><hr class="resume-classic-rule">')) throw new Error('Classic resume mockup duplicates the header separator');
  if (countFunctionDefinitions(templatesPage, 'card') !== 1 || countFunctionDefinitions(templatesPage, 'render') !== 1 || countFunctionDefinitions(templateViewerPage, 'renderTemplate') !== 1) throw new Error('Template catalog or viewer contains superseded duplicate rendering implementations');
  if (guidePage.includes('rickvang/TemplateRepo') || playbooksPage.includes('rickvang/TemplateRepo')) throw new Error('Current Site docs still present TemplateRepo as the Design System Operating Pack source');
  if (!prototypingPage.includes('Persona prototypes') || !prototypingPage.includes('proto-persona-surface-aware-partner') || !prototypingPage.includes('proto-persona-library-guide') || !prototypingPage.includes('Persona Library Guide') || !prototypingPage.includes('Selected output with missing prerequisites') || !prototypingPage.includes('Nothing is added to Personas by testing this') || !prototypingPage.includes('Promotion gate') || !prototypingPage.includes('change-reconciliation-prototype') || !prototypingPage.includes('proto-skill-change-impact-reconciliation') || !prototypingPage.includes('Generated artifact update') || !prototypingPage.includes('reconciliation report') || !prototypingPage.includes('skill-contract-prototype') || !prototypingPage.includes('proto-skill-contract-routing') || !prototypingPage.includes('Missing metadata')) throw new Error('Prototyping page is missing the isolated persona prototype workspace');
  for (const script of ['js/canvas-graph.js', 'js/canvas-intent.js', 'data/prototypes/workflow-canvas.js']) if (!canvasPage.includes(`<script src="${script}"></script>`)) throw new Error(`Workflow canvas page is missing ${script}`);
  if (!canvasPage.includes('proto-workflow-canvas-reasoning') || !canvasPage.includes('isolated prototype') || !canvasPage.includes('What this change reads as') || !canvasPage.includes('Change log') || !canvasPage.includes('Intent packet') || !canvasPage.includes('The canvas cannot answer')) throw new Error('Workflow canvas page is missing its prototype boundary or reasoning panels');
  if (!canvasPage.includes('drop-line') || !canvasPage.includes('showDropLine') || !canvasPage.includes('renderChains') || !canvasPage.includes('chain-label')) throw new Error('Workflow canvas page is missing the drop indicator or the sequence grouping');
  if (!canvasPage.includes('tabindex="0"') || !canvasPage.includes('grabCard') || !canvasPage.includes('cancelGrab') || !canvasPage.includes('id="move-status"') || !canvasPage.includes('aria-live="polite"')) throw new Error('Workflow canvas page is missing keyboard operation of the drag gesture');
  if (!canvasPage.includes('isInSequence') || !canvasPage.includes('node-links in-sequence') || !canvasPage.includes('focus-within .node-links.in-sequence') || !canvasPage.includes('Connect to')) throw new Error('Workflow canvas page is missing the connection-chip rules or the connect affordance');
  if (!canvasPage.includes('node-desc') || !canvasPage.includes('-webkit-line-clamp:2') || !canvasPage.includes('node.failureMode')) throw new Error('Workflow canvas card is missing its clamped description line');
  if (!prototypingPage.includes('workflow-canvas-prototype') || !prototypingPage.includes('proto-workflow-canvas-reasoning') || !prototypingPage.includes('workflow-canvas.html') || !prototypingPage.includes('Layout-only move') || !prototypingPage.includes('Displacement')) throw new Error('Prototyping page is missing the workflow canvas prototype');
  if (!guidePage.includes('persona-library-guide') || !guidePage.includes('Consult the Persona Library Guide') || !guidePage.includes('Prerequisite gate') || !guidePage.includes('change-reconciliation') || !guidePage.includes('$change-impact-reconciliation') || !guidePage.includes('skill-contract') || !guidePage.includes('Conditional skill contract') || !guidePage.includes('Copy prompt')) throw new Error('Docs page is missing the Persona Library Guide handoff');
  if (!guidePage.includes('agent-orientation') || !context.orientation.default_entry.includes('guide.html#agent-orientation')) throw new Error('Agent orientation must be linked from the Docs page and manifest');
  if (!guidePage.includes('routing-map') || !guidePage.includes('Persona-applied') || !guidePage.includes('$persona-panel-orchestration') || !guidePage.includes('skillLibrary') || !guidePage.includes('skill-authoring') || !guidePage.includes('$pl-skill-creator') || !guidePage.includes('PL Skill Creator') || !guidePage.includes('Bounded Parallel Implementation Playbook')) throw new Error('Docs page is missing the unified system routing map');
}
